server:
  port: 8085

filme:
  topico: filmetopico

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka      
  
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
