server:
  port: 8083
  
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
  filme:
    topico: filmetopico   
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka      
