server:
  port: 8084

spring:
  application:
    name: gateway-zuul
    
zuul:
  routes:
    index:
      sensitiveHeaders:
      path: /cadastro/**
      url: http://127.0.0.1:8081/
    bridgekc:
      sensitiveHeaders:
      path: /ordemfilme/**
      url: http://127.0.0.1:8083/
     
      
