
server:
   port: 8888

spring:
   cloud:
     config:       server:          git: 
            uri: https://github.com/BrunoCarvalho18/microservices-repo
            search-paths: usuario,filme*
            
        